CREATE table DallasMavs (id INTEGER PRIMARY KEY,first TEXT, last TEXT, age INTEGER, position TEXT);
insert into DallasMavs VALUES (1,"Dirk", "Nowitzki", 37, "PF");
insert into DallasMavs values (2,"Chandler", "Parsons", 27, "SF");
insert into DallasMavs values (3,"JJ", "Barea", 31, "PG");
insert into DallasMavs values (4,"Raymond", "Felton", 31, "PG");
insert into DallasMavs values (5,"Zaza", "Pachulia", 32, "PF");
insert into DallasMavs values (6,"Wesley", "Matthews", 29, "SG");
insert into DallasMavs values (7,"Salah", "Mejri", 29, "C"); 
insert into DallasMavs values (8,"Deron", "Williams", 31, "PG");
insert into DallasMavs values (9,"David", "Lee", 33, "C");
SELECT * FROM DallasMavs;
select * from DallasMavs where age > 30;
select * from DallasMavs where age < 30;
select first, last from DallasMavs where position = 'PF';
select AVG(age) from DallasMavs; 
select MAX(age) from DallasMavs;
select count(*) from DallasMavs;
select count(*) from DallasMavs where age = 31;
select sum(age) from DallasMavs where position = 'PG';
select count(*) from DallasMavs where age = 29; 
select position, max(age) from DallasMavs group by position;
select position,avg(age) from DallasMavs group by position;
select count(*), position from DallasMavs group by position;
select count(*), position from DallasMavs group by position having age > 30;
select count(*), position from DallasMavs group by position having age < 30;
select count(*), age from DallasMavs group by age having position = "PG";
select count(*), age from DallasMavs group by age having position = "C";
select count(*), age from DallasMavs group by age having position = "PF";
select first, last, age from DallasMavs where age > 30 order by age desc;
select first, last, age from DallasMavs where age < 30 order by age desc;
select first, last, age from DallasMavs order by age desc;
select first, last, age from DallasMavs group by age order by age desc;
select first, last, age from DallasMavs group by age having position = "PF" order by age desc;  
select first, last from DallasMavs where age > 30 and position = 'PF'; 
select first, last from DallasMavs where age < 20 or position = "PG";
select first, last, position from DallasMavs where first IN ('Dirk', 'Chandler', 'Wesley');
select last, position from DallasMavs where position IN ('SF','PF','C');
select last, position, age from DallasMavs where age BETWEEN 25 and 30;
select last, position, age from DallasMavs where age NOT BETWEEN 25 and 30;
select first, last, abs(age) from DallasMavs; 
select last, sum(age)/2 from DallasMavs;
select last, position,(age) - 6 from DallasMavs where age < 30;
create table DallasMavsWeight (DallasMavs_id INTEGER PRIMARY KEY,weight INTEGER);
Insert into DallasMavsWeight values (1,245);
insert into DallasMavsWeight values (2, 227);
insert into DallasMavsWeight values (3, 185);
insert into DallasMavsWeight values (4, 205);
insert into DallasMavsWeight values (5, 275);
insert into DallasMavsWeight values (6, 220);
insert into DallasMavsWeight values (7, 236);
insert into DallasMavsWeight values (8,209);
insert into DallasMavsWeight values (9,249);
select * from DallasMavsWeight;
select DallasMavs.first,DallasMavs.last,DallasMavsWeight.weight from DallasMavs join DallasMavsWeight on DallasMavs.id=DallasMavsWeight.DallasMavs_id;

  
